### ISSUE TITLE
Game crashes immediatelly after making a claim - also crashes whenever you try to join back

### ISSUE THREAD

**Issue by TheSusImposter** [alejandrocoria/MapFrontiers#12]
Whenever I finish making a claim in my singleplayer world, the game crashes as soon as I exit the book. Joining back will also crash the game.
I used a mod to get the crash log. I haven't seen anyone else complain about this, so it might just be me.
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 15.02.2022, 21:41
Description: Unexpected error

java.lang.NoSuchFieldError: info1Label
	at games.alejandrocoria.mapfrontiers.client.gui.GuiHUD.updateData(GuiHUD.java:341) ~[MapFrontiers-1.17.1-1.5.2.jar%2355!:1.17.1-1.5.2] {re:classloading,pl:runtimedistcleaner:A}
	at games.alejandrocoria.mapfrontiers.client.gui.GuiHUD.draw(GuiHUD.java:258) ~[MapFrontiers-1.17.1-1.5.2.jar%2355!:1.17.1-1.5.2] {re:classloading,pl:runtimedistcleaner:A}
	at games.alejandrocoria.mapfrontiers.client.gui.GuiHUD.RenderGameOverlayEvent(GuiHUD.java:162) ~[MapFrontiers-1.17.1-1.5.2.jar%2355!:1.17.1-1.5.2] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_64_GuiHUD_RenderGameOverlayEvent_Pre.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.pre(ForgeIngameGui.java:876) ~[forge-1.17.1-37.1.1-universal.jar%2361!:?] {re:classloading}
	at net.minecraftforge.client.gui.ForgeIngameGui.m_93030_(ForgeIngameGui.java:351) ~[forge-1.17.1-37.1.1-universal.jar%2361!:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:865) ~[client-1.17.1-20210706.113038-srg.jar%2357!:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1039) ~[client-1.17.1-20210706.113038-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:659) ~[client-1.17.1-20210706.113038-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2357!:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:APP:notenoughcrashes.forge.mixins.json:client.MixinMain,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.1.1.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at games.alejandrocoria.mapfrontiers.client.gui.GuiHUD.updateData(GuiHUD.java:341) ~[MapFrontiers-1.17.1-1.5.2.jar%2355!:1.17.1-1.5.2] {re:classloading,pl:runtimedistcleaner:A}
	at games.alejandrocoria.mapfrontiers.client.gui.GuiHUD.draw(GuiHUD.java:258) ~[MapFrontiers-1.17.1-1.5.2.jar%2355!:1.17.1-1.5.2] {re:classloading,pl:runtimedistcleaner:A}
	at games.alejandrocoria.mapfrontiers.client.gui.GuiHUD.RenderGameOverlayEvent(GuiHUD.java:162) ~[MapFrontiers-1.17.1-1.5.2.jar%2355!:1.17.1-1.5.2] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.eventbus.ASMEventHandler_64_GuiHUD_RenderGameOverlayEvent_Pre.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.pre(ForgeIngameGui.java:876) ~[forge-1.17.1-37.1.1-universal.jar%2361!:?] {re:classloading}
	at net.minecraftforge.client.gui.ForgeIngameGui.m_93030_(ForgeIngameGui.java:351) ~[forge-1.17.1-37.1.1-universal.jar%2361!:?] {re:classloading}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['TheSusImposter'/117, l='ClientLevel', x=-532.37, y=90.12, z=978.78]]
	Chunk stats: 529, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (-256,70,32), Section: (at 0,6,0 in -16,4,2; chunk contains blocks -256,0,32 to -241,255,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2503733 game time, 7315 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:364) ~[client-1.17.1-20210706.113038-srg.jar%2357!:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2245) ~[client-1.17.1-20210706.113038-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:681) ~[client-1.17.1-20210706.113038-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:186) ~[client-1.17.1-20210706.113038-srg.jar%2357!:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:APP:notenoughcrashes.forge.mixins.json:client.MixinMain,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.17.1-37.1.1.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Mod Resources, Default

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 418257272 bytes (398 MiB) / 1677721600 bytes (1600 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-2320 CPU @ 3.00GHz
	Identifier: Intel64 Family 6 Model 42 Stepping 7
	Microarchitecture: Sandy Bridge (Client)
	Frequency (GHz): 2,99
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GT 630
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 1024,00
	Graphics card #0 deviceId: 0x0f00
	Graphics card #0 versionInfo: DriverVersion=23.21.13.8813
	Memory slot #0 capacity (MB): 4096,00
	Memory slot #0 clockSpeed (GHz): 1,33
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096,00
	Memory slot #1 clockSpeed (GHz): 1,33
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 15814,09
	Virtual memory used (MB): 9238,02
	Swap memory total (MB): 7680,00
	Swap memory used (MB): 164,18
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.17.1-forge-37.1.1
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: GeForce GT 630/PCIe/SSE2 GL version 3.2.0 NVIDIA 388.13, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: mod_resources, vanilla
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-2320 CPU @ 3.00GHz
	Player Count: 1 / 8; [ServerPlayer['TheSusImposter'/117, l='ServerLevel[world]', x=-532.37, y=90.12, z=978.78]]
	Data Packs: vanilla, file/bukkit, mod:forge, mod:journeymap (incompatible), mod:mapfrontiers (incompatible), mod:journeymapadditions (incompatible), mod:notenoughcrashes (incompatible)
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 capability_inject_definalize PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		journeymap-additions-1.17.1-0.0.3.jar             |Journeymap Additions          |journeymapadditions           |1.17.1-0.0.3        |DONE      |Manifest: NOSIGNATURE
		notenoughcrashes-4.1.4+1.17.1-forge.jar           |Not Enough Crashes            |notenoughcrashes              |4.1.4+1.17.1        |DONE      |Manifest: NOSIGNATURE
		forge-1.17.1-37.1.1-universal.jar                 |Forge                         |forge                         |37.1.1              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		MapFrontiers-1.17.1-1.5.2.jar                     |MapFrontiers                  |mapfrontiers                  |1.17.1-1.5.2        |DONE      |Manifest: NOSIGNATURE
		journeymap-1.17.1-5.8.0beta15.jar                 |Journeymap                    |journeymap                    |5.8.0beta15         |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: c2771029-540a-47cd-bd4a-d75b177b5203
	FML: 37.1
	Forge: net.minecraftforge:37.1.1
	Suspected Mods: MapFrontiers (mapfrontiers), Minecraft (minecraft), Forge (forge)

**Comment by alejandrocoria** [comment]
Please use the recommended JourneyMap version: 1.17.1-5.7.3.

**Comment by TheSusImposter** [comment]
The latest version for 1.17.1 on CF is 1.5.2. Do I have to go to some other site to download it?

**Comment by TheSusImposter** [comment]
Nevermind, got it mixed up. You were talking about JM, not MF.

**Comment by TheSusImposter** [comment]
Yeah, that fixed it. Thanks.
