### ISSUE TITLE
Game crashes on startup using either 1.21 beta (FABRIC)

### ISSUE THREAD

**Issue by SirCrux** [alejandrocoria/MapFrontiers#51]
As stated, trying to launch with either fabric 1.21 beta just crashes the game before the loading screen shows up with no error message on exit. Is there some incompatibility with something else I may have? Is there a latest version of JourneyMap I should install? Or is this something I did wrong? And yes, I tried removing several mods to find the culprit and it only launched properly when MapFrontiers was removed which sucks since I was excited for it to be on the latest version.

**Comment by alejandrocoria** [comment]
Please put the latest.log here after causing the crash.

**Comment by SirCrux** [comment]
> Please put the latest.log here after causing the crash.

where would I find that? The crash message only says "An unexpected error has occurred and the game has crashed. We are sorry for the inconvenience."

**Comment by alejandrocoria** [comment]
You can find the file in the logs folder in the game folder.

**Comment by SirCrux** [comment]
> You can find the file in the logs folder in the game folder.

I looked for the lines pertaining to Journeymap and got these:

[23:25:43] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.15.11
[23:25:43] [ForkJoinPool-1-worker-1/WARN]: Mod cpm uses the version 0.6.17b which isn't compatible with Loader's extended semantic version format (Could not parse version number component '17b'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[23:25:43] [ForkJoinPool-1-worker-2/WARN]: Mod mapfrontiers uses the version 2.6.0beta2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component '0beta2'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[23:25:44] [main/WARN]: Warnings were found!

[23:26:11] [Render thread/WARN]: Removed resource pack mapfrontiers from options because it is no longer compatible

[23:26:16] [Render thread/INFO]: Found @JourneyMapPlugin: games.alejandrocoria.mapfrontiers.client.plugin.MapFrontiersPlugin
[23:26:16] [Render thread/INFO]: [STDERR]: java.lang.NoSuchFieldError: Class journeymap.api.v2.common.event.ClientEventRegistry does not have member field 'journeymap.api.v2.common.event.impl.Event FULLSCREEN_MAP_CLICK_EVENT'
[23:26:16] [Render thread/INFO]: [STDERR]: 	at games.alejandrocoria.mapfrontiers.client.plugin.MapFrontiersPlugin.initialize(MapFrontiersPlugin.java:29)
[23:26:16] [Render thread/INFO]: [STDERR]: 	at journeymap.api.v2.client.util.PluginHelper.initPlugins(PluginHelper.java:166)
[23:26:16] [Render thread/INFO]: [STDERR]: 	at journeymap.client.JourneymapClient.init(JourneymapClient.java:133)
[23:26:16] [Render thread/INFO]: [STDERR]: 	at journeymap.client.JourneymapClientFabric.lambda$onInitializeClient$0(JourneymapClientFabric.java:23)

net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchFieldError: Class journeymap.api.v2.common.event.ClientEventRegistry does not have member field 'journeymap.api.v2.common.event.impl.Event FULLSCREEN_MAP_CLICK_EVENT'
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]

Caused by: java.lang.NoSuchFieldError: Class journeymap.api.v2.common.event.ClientEventRegistry does not have member field 'journeymap.api.v2.common.event.impl.Event FULLSCREEN_MAP_CLICK_EVENT'
	at games.alejandrocoria.mapfrontiers.client.plugin.MapFrontiersPlugin.initialize(MapFrontiersPlugin.java:29) ~[MapFrontiers-1.21-2.6.0beta2-fabric.jar:?]
	at journeymap.api.v2.client.util.PluginHelper.initPlugins(PluginHelper.java:166) ~[journeymap-api-fabric-2.0.0-1.21-SNAPSHOT-6919460b9568e319.jar:?]
	at journeymap.client.JourneymapClient.init(JourneymapClient.java:133) ~[journeymap-fabric-1.21-6.0.0-beta.7.jar:?]
	at journeymap.client.JourneymapClientFabric.lambda$onInitializeClient$0(JourneymapClientFabric.java:23) ~[journeymap-fabric-1.21-6.0.0-beta.7.jar:?]

**Comment by alejandrocoria** [comment]
Try updating MapFrontiers and JourneyMap to the latest version.

**Comment by SirCrux** [comment]
> Try updating MapFrontiers and JourneyMap to the latest version.

That solved it, I was using JourneyMap beta7 :/
Thank you for your help and punctuality ^-^

**Comment by alejandrocoria** [comment]
You are welcome.
